#!/usr/bin/perl -w
# -*- perl -*-
# vim: ft=perl

=head1 NAME

snmp__load-rtx - Munin plugin to monitor Yamaha RTX1200 load average via SNMP.

=head1 APPLICABLE SYSTEMS

Any SNMP-capable device that reports the YAMAHA-RT-HARDWARE::yrhCpuUtil*****.0
OID.  This includes those running the SNMPd provided by the
Net-SNMP project.

=head1 CONFIGURATION

As a rule SNMP plugins need site specific configuration.  The default
configuration (shown here) will only work on insecure sites/devices.

   [snmp_*]
	env.version 2
        env.community public

In general SNMP is not very secure at all unless you use SNMP version
3 which supports authentication and privacy (encryption).  But in any
case the community string for your devices should not be "public".

Please see 'perldoc Munin::Plugin::SNMP' for further configuration
information.

=head1 INTERPRETATION

CPU load show as a paercentage.

=head1 MIB INFORMATION

1.3.6.1.4.1.1182.2.1.5.0 (YAMAHA-RT-HARDWARE::yrhCpuUtil5sec.0) = Gauge32
1.3.6.1.4.1.1182.2.1.6.0 (YAMAHA-RT-HARDWARE::yrhCpuUtil1min.0) = Gauge32
1.3.6.1.4.1.1182.2.1.7.0 (YAMAHA-RT-HARDWARE::yrhCpuUtil5min.0) = Gauge32


=head1 MAGIC MARKERS

  #%# family=snmpauto
  #%# capabilities=snmpconf

=head1 VERSION

  $Id$

=head1 BUGS

None known.

=head1 AUTHOR

Copyright (C) 2013 Nobuyuki Furuyama

=head1 LICENSE

GPLv2.

=cut

use strict;
use Munin::Plugin::SNMP;

if (defined $ARGV[0] and $ARGV[0] eq 'snmpconf') {
	# .iso.org.dod.internet.private.enterprises.ucdavis.laTable.laEntry.laLoad.2
	# (5-minute average)
	print "require 1.3.6.1.4.1.1182.2.1.5.0\n";
	print "require 1.3.6.1.4.1.1182.2.1.6.0\n";
	print "require 1.3.6.1.4.1.1182.2.1.7.0\n";
	exit 0;
}

if (defined $ARGV[0] and $ARGV[0] eq "config") {
	my ($host) = Munin::Plugin::SNMP->config_session();

	print "host_name $host\n" unless $host eq 'localhost';
	print <<"EOC";
graph_title Load average
graph_args -l 0 --upper-limit 100
graph_vlabel Percent
graph_category system
graph_info This graph shows the load average on the host. Load average is a rough way of estimating how hard the machine works. Optimally, a load average should be equal to or lower than the number of CPUs on the machine.
load5sec.label load5sec
load5sec.info The load average itself. This number is an average of the last 5 seconds.
load5sec.draw LINE2
load1min.label load1min
load1min.info The load average itself. This number is an average of the last 1 minutes.
load1min.draw LINE2
load5min.label load5min
load5min.info The load average itself. This number is an average of the last 5 minutes.
load5min.draw LINE2
EOC
	exit 0;
}

my $session = Munin::Plugin::SNMP->session();
print "load5sec.value ", $session->get_single('1.3.6.1.4.1.1182.2.1.5.0'), "\n";
print "load1min.value ", $session->get_single('1.3.6.1.4.1.1182.2.1.6.0'), "\n";
print "load5min.value ", $session->get_single('1.3.6.1.4.1.1182.2.1.7.0'), "\n";

