#!/usr/bin/perl -w
# -*- perl -*-

=head1 NAME

snmp__memory-rtx - Munin plugin to monitor memory usage of a remote Yamaha RTX1200
via SNMP.

=head1 CONFIGURATION

The following configuration variables are used

 host      - SNMP host to contact (default taken from link name)
 port      - SNMP port to use (default 161)
 community - SNMP community string to use (default "public")

=head1 NOTES

Based on snmp__df plugin.... If this plugin reports
different numbers from the snmp_winmem plugin it must be due
to snmp impementation quirks....

=head1 AUTHOR

Copyright (C) 2013 Nobuyuki Furuyama

=head1 LICENSE

GPLv2.

=head1 MAGIC MARKERS

 #%# family=snmpauto
 #%# capabilities=snmpconf

=cut

use strict;
use Munin::Plugin::SNMP;


# memory usage pr. process
my $hrSWRunPerfMem = "1.3.6.1.4.1.1182.2.1.4.0";

if (defined $ARGV[0] and $ARGV[0] eq "snmpconf")
{
    print "require $hrSWRunPerfMem\n";
    exit 0;
}

my $session = Munin::Plugin::SNMP->session();

if (defined $ARGV[0] and $ARGV[0] eq "config")
{
    my ($host) = Munin::Plugin::SNMP->config_session();
    print "host_name $host\n";
    print "graph_title Memory usage\n";
    print "graph_category system\n";
    print "graph_vlabel Percent\n";
    print "graph_info This grap shows memory usage.\n";
	print "graph_args -l 0 --upper-limit 100\n";
    print "memory.draw AREA\n";
    print "memory.label memory\n";
   
    exit 0;
}

# calculate total memory
#my $processes = $session->get_by_regex ($hrSWRunPerfMem, "[1-9]");
my $processes = $session->get_single ($hrSWRunPerfMem);

print "memory.value $processes\n";
